version: "3.7"
services:
  mysql_debezium:
    container_name: mysql_debezium
    image: debezium/example-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: debezium
      MYSQL_PASSWORD: debezium
    ports:
      - "3306:3306"

  connect_debezium:
    container_name: connect_debezium
    image: debezium/connect:1.3
    environment:
      - BOOTSTRAP_SERVERS=kafka_debezium:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_configs
      - OFFSET_STORAGE_TOPIC=debezium_offsets
      - STATUS_STORAGE_TOPIC=debezium_statuses
    ports:
      - 8083:8083
    links:
      - kafka_debezium
      - mysql_debezium
    depends_on:
      - kafka_debezium
      - zookeeper_debezium
      - mysql_debezium

  zookeeper_debezium:
    container_name: zookeeper_debezium
    image: debezium/zookeeper:1.1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka_debezium:
    container_name: kafka_debezium
    image: debezium/kafka:1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper_debezium
    environment:
      ZOOKEEPER_CONNECT: zookeeper_debezium:2181

  kafdrop_debezium:
    container_name: kafdrop_debezium
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
      KAFKA_BROKERCONNECT: kafka_debezium:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka_debezium

  mongodb_debezium:
    container_name: mongodb_debezium
    image: mongo:4.4.0-rc12-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: cadastro
      MONGO_INITDB_ROOT_PASSWORD: cadastro123456
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"